### PR TITLE
Object view error checking and path parsing

### PR DESCRIPTION
**Pull request by krl**
Add a ipfs permalink for ipns data:

ipns-path-permalink

Data does not display a big empty box when empty:
permalink-data

Error handling: (see #49)

error-handling

These things are moving towards #43

### CODE REVIEW

**Comment by krl** [comment]
btw, the font issues only appear when i run in dev-mode, looking at this too

**Comment by jbenet** [comment]
right now, the links + data boxes are a bit odd -- doesn't feel like a single object. wonder if pushing them together may be a good visual, something like: 



but with better indicators / headers or whatever

**Comment by krl** [comment]
new-object-links

new-object-data

Some alignment improvements, proposed grouping-of-objects.

**Comment by krl** [comment]
Changed 'go back' into 'Parent object', which is more to the point.

Not using 'window.location.hash = something' anymore, but context.router.transitionTo()

Moved path parsing into its own utils/path.js for use in other parts of the app

**Comment by jbenet** [comment]
@krl these changes looks great to me -- thanks for the screenshots. 


- i really like the combined links + data box. + love that you clearly tell the user that it's empty. :+1:  
- the permalink probably should be outside still, sorry for not being clear. it could also have a "copy" button like other places in the ui.
- i'd prefer -- when there is data -- for the data to occupy the whole box, instead of having the word "Data" and the actual data nested one more box deeper. looks too complex.

For example:



totally right that we need to clarify the difference between the two segments to people, so maybe we could do something like:

image

where the `xml protobuf json` links change the encoding in place, and the "external link" is a link to `/object/data?arg=<key>&enc=<encoding>` (in the api route for now, later on we can see about exposing read only things like `/object/data` to the normal gateway, or something).

### we can probably address these things in a separate PR-- whatever you prefer. I'm good to merge as is or fix.

---

(( disclaimer for my pedantic stylistic nits: sorry to go back and forth on it, since i designed lots of the UX here (along with a designer) i'm going to claim responsibility for it. most of it doesn't matter but some things (even small) like the placement of boxes have strong implications in terms of people's understanding of things. i think right now i have the most cohesive perspective into all the ipfs touch points and can probably make the most informed decisions. i hope to defer all this to a full time designer once we get one. ))

**Comment by krl** [comment]
3objectview

3objectview2

Still not 100% sure about the headings, IANRAD either, but i think this addresses your stylistic comments.

Pedantic is good!

**Comment by krl** [comment]
Btw, json/protobuf/xml viewer is also something i think we should have here.

**Comment by jbenet** [comment]
LGTM

**Comment by jbenet** [comment]
thanks for making the design changes! :+1:

**Pull request merged**
