### PR TITLE
Fix DagPath on UI

### PR DESCRIPTION
**Pull request by Atinux**
Hi, your DAG link was broken, it has to link to #/objects/object/{object.id}

BTW, your IPFS protocol is awesome =)

### CODE REVIEW

**Comment by jbenet** [comment]
Ah, thanks. Can someone else confirm this fixes the webui?

**Comment by Atinux** [comment]
I made a video for you to see the fix in action :smile: 

[dGtpchDi5k8](http://www.youtube.com/watch?v=dGtpchDi5k8)

**Comment by jbenet** [comment]
hahah thanks

**Comment by jbenet** [comment]
it should go out in the next go-ipfs release.

**Pull request merged**
