### PR TITLE
Converted majority of BS elements

### PR DESCRIPTION
**Pull request by RichardLitt**
Converted most of the BS elements to ReactBootstrap, as per #140. I did not do all of them - I am not sure how Button would react, for instance, and I want to make sure I do it right before I mess something up.

### CODE REVIEW

**Comment by RichardLitt** [comment]
@Dignifiedquire Fixed linting error.

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by RichardLitt** [comment]
Passed. This should be merged before more work is done on the `webpack` branch.

**Comment by Dignifiedquire** [comment]
Done :)

**Pull request merged**
