### PR TITLE
[FIX] Add gulp-util to dev dependencies

### PR DESCRIPTION
**Pull request by stevenzeiler**
Otherwise build does not work out of the box

### CODE REVIEW

**Comment by jbenet** [comment]
is this still needed? cc @travisperson

**Comment by travisperson** [comment]
I don't believe so, I haven't had any issues. @stevenzeiler what issues were you running into? I don't see where gulp-utils was being used.

**Comment by travisperson** [comment]
I think this can be closed.

@jbenet.

**Comment by jbenet** [comment]
Ok

**Pull request closed without merging**
