### PR TITLE
I18n support + Czech localization

### PR DESCRIPTION
**Pull request by digital-dreamer**
The interface can now be translated into various languages using JSON files placed in /static/locale. To test it, first change your web browser's preferred language to Czech, and then open the webui.

If you agree, I will also create a translation project on Transifex to keep track of new languages and source string additions / changes. The library I used supports GNU gettext tools, which makes maintaining translations much easier than if you edit the JSON files by hand.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks for this contribution. I really like this, and the library looks pretty good with relative little overhead inside the code. 

What do you think @jbenet @diasdavid about this?

**Comment by diasdavid** [comment]
This is awesome! Thank you @digital-dreamer LVGTM :)

**Comment by digital-dreamer** [comment]
@Dignifiedquire & @diasdavid Thanks :-) So I'll now use the .pot template to create a crowdsourced translation project, is that OK with you? I already did this for 3 other projects (GNU social, Impleller and Lighthouse), so I'm familiar with the workflow.

**Comment by Dignifiedquire** [comment]
I'm afraid I have no idea what a `.pot template` is, but it sounds good :laughing:

**Comment by digital-dreamer** [comment]
:laughing: Portable object template is a file used to generate new localizations, it's a format used by GNU gettext. Don't worry, I'll take care of it, I just wanted to ask for permission, since I'm new to the project.

**Comment by digital-dreamer** [comment]
OK, done: https://www.transifex.com/ipfs/ipfs-webui/

**Comment by Dignifiedquire** [comment]
Thanks @digital-dreamer :)

**Comment by digital-dreamer** [comment]
@Dignifiedquire Do you want to be a maintainer? It allows you to accept language request, manage team members, etc.

**Comment by Dignifiedquire** [comment]
@digital-dreamer that would be good yes

**Comment by jbenet** [comment]
localization is great! :)

**Comment by digital-dreamer** [comment]
@jbenet Thanks :smiley: BTW I just resolved the merge conflict, it happened because commit 550dd4ba7f7825bdad67c66628c66f14938f07f2 "update font-awesome to version 4.5.0" changed package.json after I submitted my pull request. GitHub shows this branch is now compatible with master. So can we merge it?

**Comment by jbenet** [comment]
@digital-dreamer excellent! LGTM, others?

Q: what's the protocol for changing things? i would like to be able to freely change the webui without having all the internationalized differences in. but i dont want to be a jerk to everyone else.

**Comment by jbenet** [comment]
(i'm _all_ for accessibility, but the team is very small so i dont want to burden people with hard-to-change things)

**Comment by digital-dreamer** [comment]
@jbenet - If you want to make a change in the text without adding it to the source strings, you can just put it directly in the code without calling i18n.t - the difference would be minimal, since the new string would be English-only anyway until someone translates it. I'll be automatically updating the source strings after significant UI changes, putting some i18n.t functions back is not much work.

Before the translators update their languages, they can be incomplete (for example the whole UI is in Spanish, but one button for a new feature still has an English label), but even such an incomplete translation is far more accessible for people who don't speak English, and there is a lot of them in the world - we need to make IPFS international before we can go interplanetary :smile:

**Comment by Dignifiedquire** [comment]
Lgtm :) looking at the overhead it looks easy enough. The only thing that would be good is a description for developers how to use this in CONTRIBUTING.md.

**Comment by fazo96** [comment]
Hi :) I'd like to maintain an italian translation for the web UI since it's my native language, I made a proposal on transifex. If you guys accept I can be a translator :+1:

**Comment by digital-dreamer** [comment]
Hi @fazo96, I just confirmed your request, welcome to the team :+1: 

For others who would like to participate too, the URL is https://www.transifex.com/ipfs/ipfs/

I removed the -webui in the project name because I realized it made no sense to have 2 separate projects for WebUI and instructions.

**Comment by jbenet** [comment]
- [ ] +1 to note in `CONTRIBUTING.md`

**Comment by digital-dreamer** [comment]
OK, you mean something like this? There was no contributing file in this repo, so I created a new one.

**Comment by jbenet** [comment]
@digital-dreamer yep, that's right! ok thanks-- i'm good to merge this. others?

**Comment by Dignifiedquire** [comment]
Let's merge this, there are already a couple of translations in progress on the transifex

**Comment by harlantwood** [comment]
Awesome work, next step interplanetary languages! :smile:

**Pull request merged**
