### PR TITLE
Removed jQuery from linkHandler

### PR DESCRIPTION
**Pull request by RichardLitt**
Don't have time for much more today, but this should work. I'm not sure how to test it, though. Related to #133

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
I think we can actually drop this linkhandler module completely if we move to the latest react-router

**Comment by Dignifiedquire** [comment]
Actually it's already commented out and not required, just pushed a removal of it. Sorry :blush:

**Comment by RichardLitt** [comment]
@Dignifiedquire I've seen this sort of linkhandler a few places. Can you explain why it was necessary?

**Comment by RichardLitt** [comment]
I keep running across this thing, anyway, so I made it into the [react-linkhandler](https://github.com/RichardLitt/react-linkhandler) module.

**Comment by Dignifiedquire** [comment]
I actually don't understand why it was necessary. For all links that should be handled by `react-router` one uses `import {Link} from 'react-router'` and for all regular links you use `<a href='..'></a>` as in regular html

**Comment by RichardLitt** [comment]
@jbenet You originally created this. Can you explain why?

**Comment by RichardLitt** [comment]
@jbenet put it in Beagle too. I just modularized it there, don't know why I didn't do that earlier. I don't think I was as modular-friendly as I am now. Cf: https://github.com/BeagleLab/beagle/blob/master/js/main.js#L11

**Comment by Dignifiedquire** [comment]
Strange, makes no sense to me as explained above

**Pull request closed without merging**
