### PR TITLE
Version 0.2.0

### PR DESCRIPTION
**Pull request by krl**
- [x] publish webui
- [ ] test ux
```
ipfs daemon --unrestricted-api
```
then go to: http://localhost:5001/ipfs/QmVTW3rXyfHBbz9Tg5gAXhkhbrEF8rJFzgLdigAaRLEk4H
- [x] pin hash
- [ ] update in go-ipfs

### CODE REVIEW

**Comment by jbenet** [comment]
pinned on pinbot and celebdil. also added to infrastructure: https://github.com/ipfs/infrastructure/commit/9ae6dcd

**Comment by jbenet** [comment]
@krl could you give me a list of things to test in terms of UX?

**Comment by travisperson** [comment]
None of the copy to clipboard links work anymore for me.

**Comment by krl** [comment]
i am 100% sure i actually commented on this. wifi must have eaten it or something.

What i said was roughly, i don't really use flash personally, and i have not, as far as i know, touched that part of the code, but i will have a look.

I would also be in favor of removing this feature, since it depends on flash, and i think we should keep non-free dependencies out of the project.

I don't see a huge use case for this either (my mom knows how ctrl-c, ctrl-v works).

How do you feel about this? @tperson @jbenet

**Comment by whyrusleeping** [comment]
is there no way to do that without flash?

**Comment by krl** [comment]
Ok, so i pulled out the flash dependency, here's the new uri:

http://localhost:5001/ipfs/QmX4eQoPToCURdzuS8ddj11ve3xYqSotswzsZWp2TTFkxJ

**Comment by krl** [comment]
ping, anything else?

**Comment by jbenet** [comment]
discussion from irc:

```
16:17 <krl> jbenet: would be nice if we could get the webui update merged soon too, did you do a diff on what your webui build resulted in? 
16:26 → G-Ray joined (~geoffrey@2a01:e35:2ed6:3f50:da50:e6ff:fe3d:e9c6)
16:40 <•jbenet> kyledrake that's awesome
16:41 <•jbenet> kyledrake want to make it a shell script -- maybe `ipfs-nc-push` ?  (we'll have a proper push later)
16:41 <•jbenet> or ipfs-nc-pull
16:41 <•jbenet> krl: that's fantastic to hear!
16:41 <•jbenet> krl: making a repo-- sec.
16:41 <•jbenet> lol <3 wizard
16:42 <•jbenet> krl: i'll do a webui diff now
16:43 <•jbenet> krl: https://github.com/ipfs/ipfs-electron
16:44 <•jbenet> maybe rename it to just electron-app ?
16:44 <•jbenet> renamed https://github.com/ipfs/electron-app
16:54 → Tv` joined (uid62079@gateway/web/irccloud.com/x-gypxbxmbizxhwscb)
16:55 <•jbenet> krl the diff is huge, because of standard. did you do `make publish`? not sure if it ran for you.
16:56 <•jbenet> krl: http://gateway.ipfs.io/ipfs/QmU5cVGVhMKuR2KsjWwzzws8EvWEHKMkG5WYEAmbEG8qVB/diff
16:56 <krl> jbenet: i mean, you told me you got a different build formmaster
16:56 <krl> eh, not master, the v0.2.0 branch
16:56 <•jbenet> krl: yeah 0.2.0
16:56 <krl> mine was QmX4eQoPToCURdzuS8ddj11ve3xYqSotswzsZWp2TTFkxJ
16:56 <•jbenet> right mine was QmTCggsf8fJPijYfYgtoSRzFPNxKEWBhLrKrJzUVDUQCWA
16:57 <•jbenet> see the very last part of that diff
16:57 <•jbenet> mine (QmTCggsf8fJPijYfYgtoSRzFPNxKEWBhLrKrJzUVDUQCWA) doesnt have semicolons and yours does
16:58 <krl> the diff is between two builds in v0.2.0, or between v0.2.0 and master?
16:58 <•jbenet> i built v0.2.0
16:58 <•jbenet> (i assume you did too)
16:58 <krl> yes, and got semicolons??
16:58 <•jbenet> i didn't-- looks like you did
16:58 <krl> :/
16:59 <krl> strange
16:59 <•jbenet> see the very very last part of the diff i linked o/
16:59 <krl> yeah.
16:59 <krl> ok, but i'll have to go now, i'll have more late-time tomorrow
16:59 <krl> maybe we can wrap these things up then
16:59 <•jbenet> ok
17:00 <•jbenet> yeah sounds good
17:00 <•jbenet> o/
17:00 <•jbenet> krl: if want to merge this, i can publish it, but we should figure out why it's different, etc
17:01 <krl> yeah
17:01 <krl> i'm fine either way
17:01 <krl> but we should really pursue reproducible builds wherever we can
17:01 <•jbenet> yeah exactly
17:01 <•jbenet> i'm happy to wait
17:01 <•jbenet> no rush
```

**Pull request merged**
