### PR TITLE
feat: Replace console.log with debug

### PR DESCRIPTION
**Pull request by Dignifiedquire**
This is the setup for #151. The actual good logging messages still need to be written at a later point

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
After some discussion on IRC we might go with `debug` needs more research

**Comment by Dignifiedquire** [comment]
Changed to `debug` as that seems to be the choice these days and it supports `stderr` in node.

**Comment by Dignifiedquire** [comment]
@RichardLitt can you review this one as well and merge if you are happy?

**Comment by RichardLitt** [comment]
Everybody wins.

**Pull request merged**
