### PR TITLE
Update french translation

### PR DESCRIPTION
**Pull request by cedrou**
Update french locale file with better translations

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Sorry @Stebalien, I don't speak French :( 

I do think @josselinchevalay can help out reviewing this though!

**Comment by josselinchevalay** [comment]
Hello,
Yes i Can help on that let me know how tout do that

Regards

Le 12 déc. 2017 18:42, "ᴠɪᴄᴛᴏʀ ʙᴊᴇʟᴋʜᴏʟᴍ" <notifications@github.com> a
écrit :

**Comment by josselinchevalay** [comment]
Ok i see your commit , Nice good work :+1:

**Comment by Stebalien** [comment]
@josselinchevalay, @cedrou,

Thanks!

**Pull request merged**
